[workspace]
default-members = ["chargelimit-selinux"]
members = ["chargelimit-selinux"]
resolver = "2"

[workspace.package]
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
repository = "https://github.com/chenxiaolong/ChargeLimit"
publish = false
