#!/sbin/sh

# SPDX-FileCopyrightText: 2022-2024 Andrew Gunnerson
# SPDX-License-Identifier: GPL-3.0-only
# Based on BCR code.

OUTFD=${2}
ZIPFILE=${3}

umask 022

ui_print() {
    printf "ui_print %s\nui_print\n" "${*}" > /proc/self/fd/"${OUTFD}"
}

if [ -f /sbin/recovery ] || [ -f /system/bin/recovery ]; then
    # Installing via recovery.

    ui_print 'Installing from recovery is not supported'
    exit 1
else
    # Installing via Magisk Manager.

    if [ "$(getprop init.svc.google_battery)" != "running" ]; then
        ui_print 'google_battery HAL not found'
        ui_print 'Not supported on this device'
        exit 1
    fi

    . /data/adb/magisk/util_functions.sh
    install_module
fi
